version: '3'
services:
  es-query:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0-SNAPSHOT
    environment:
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - ./query-config:/usr/share/elasticsearch/config
    networks:
      - esnet
  k-query:
    image: docker.elastic.co/kibana/kibana:8.14.0-SNAPSHOT #make sure you login: https://docker-auth.elastic.co/github_auth
    ports:
      - "5601:5601"
    volumes:
      - ./query-config/kibana.yml:/usr/share/kibana/config/kibana.yml 
    depends_on:
      - es-query
    networks:
      - esnet    

 # second cluster
  es-fulfill:
    image: elasticsearch:8.12.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 19200:9200
      - 19443:9443
    volumes:
      - ./fulfill-config:/usr/share/elasticsearch/config
    depends_on:
      - es-query   
    networks:
      - esnet
  k-fulfill:
    image: kibana:8.12.0
    ports:
      - "15601:5601"
    volumes:
      - ./fulfill-config/kibana.yml:/usr/share/kibana/config/kibana.yml 
    depends_on:
      - es-fulfill
    networks:
      - esnet       
     
networks:
  esnet:
