version: '3'
services:
  es-query:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0-SNAPSHOT
    environment:
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.untrusted_remote_cluster_feature_flag_registered=true"
    ports:
      - 9200:9200
    volumes:
      - ./es-query.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch.keystore.query:/usr/share/elasticsearch/config/elasticsearch.keystore
      - ./log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./service_tokens:/usr/share/elasticsearch/config/service_tokens 
    networks:
      - esnet
  k-query:
    image: docker.elastic.co/kibana/kibana:8.10.0-SNAPSHOT 
    ports:
      - "5601:5601"
    volumes:
      - ./k-query.yml:/usr/share/kibana/config/kibana.yml 
    depends_on:
      - es-query
    networks:
      - esnet    

  # second cluster
  es-fulfill:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0-SNAPSHOT
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.untrusted_remote_cluster_feature_flag_registered=true"
    ports:
      - 19200:9200
    volumes:
      - ./es-fulfill.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch.keystore.fulfill:/usr/share/elasticsearch/config/elasticsearch.keystore
      - ./log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./service_tokens:/usr/share/elasticsearch/config/service_tokens
    depends_on:
      - es-query   
    networks:
      - esnet
  k-fulfill:
    image: docker.elastic.co/kibana/kibana:8.10.0-SNAPSHOT 
    ports:
      - "15601:5601"
    volumes:
      - ./k-fulfill.yml:/usr/share/kibana/config/kibana.yml 
    depends_on:
      - es-fulfill
    networks:
      - esnet       
     
networks:
  esnet:
